# Generated by Django 4.1.7 on 2023-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Site name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone number')),
                ('img', models.ImageField(upload_to='images', verbose_name='Logo')),
                ('facebook', models.URLField(verbose_name='Facebook link')),
                ('twitter', models.URLField(verbose_name='Twitter link')),
                ('linkedin', models.URLField(verbose_name='Linkedin link')),
                ('dribbble', models.URLField(verbose_name='Dribbble link')),
                ('google_plus', models.URLField(verbose_name='Google-plus link')),
                ('country1', models.CharField(max_length=50, verbose_name='Country 1')),
                ('country2', models.CharField(max_length=50, verbose_name='Country 2')),
                ('country3', models.CharField(max_length=50, verbose_name='Country 3')),
                ('curency1', models.CharField(max_length=50, verbose_name='CUrency 1')),
                ('curency2', models.CharField(max_length=50, verbose_name='CUrency 2')),
                ('curency3', models.CharField(max_length=50, verbose_name='CUrency 3')),
                ('account', models.CharField(max_length=50, verbose_name='accaunt')),
                ('wishlist', models.CharField(max_length=50, verbose_name='wishlist')),
                ('checkout', models.CharField(max_length=50, verbose_name='checkout')),
                ('cart', models.CharField(max_length=50, verbose_name='cart')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('logout', models.CharField(max_length=50, verbose_name='logout')),
                ('signup', models.CharField(max_length=50, verbose_name='signup')),
            ],
            options={
                'verbose_name': 'HeaderInfo',
                'verbose_name_plural': 'HeaderInfo',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
