# Generated by Django 4.1.7 on 2023-04-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_headerinfo_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerinfo',
            name='country1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country 1'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='country2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country 2'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='country3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Country 3'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency1',
            field=models.CharField(blank=True, max_length=50, verbose_name='CUrency 1'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency2',
            field=models.CharField(blank=True, max_length=50, verbose_name='CUrency 2'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency3',
            field=models.CharField(blank=True, max_length=50, verbose_name='CUrency 3'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='dribbble',
            field=models.URLField(blank=True, verbose_name='Dribbble link'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook link'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='google_plus',
            field=models.URLField(blank=True, verbose_name='Google-plus link'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin link'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='Twitter link'),
        ),
    ]
