# Generated by Django 4.1.7 on 2023-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_headerinfo_country1_alter_headerinfo_country2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='email',
            field=models.URLField(null=True, verbose_name='Email adress'),
        ),
    ]
