# Generated by Django 4.1.7 on 2023-04-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_homeslider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSliderActive',
        ),
        migrations.RenameField(
            model_name='homeslider',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='homeslider',
            old_name='img2',
            new_name='img_logo',
        ),
    ]
