# Generated by Django 4.1.7 on 2023-04-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_homeslideractive_rename_img1_homeslider_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Category name')),
                ('name_hy', models.CharField(max_length=60, null=True, verbose_name='Category name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='Category name')),
                ('classname', models.CharField(max_length=60, verbose_name='Class name')),
                ('classname_hy', models.CharField(max_length=60, null=True, verbose_name='Class name')),
                ('classname_en', models.CharField(max_length=60, null=True, verbose_name='Class name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='SubCategory name')),
                ('name_hy', models.CharField(max_length=60, null=True, verbose_name='SubCategory name')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='SubCategory name')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='SubCategory price')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='SubCategory image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
            },
        ),
    ]
