# Generated by Django 4.1.7 on 2023-04-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='classname',
        ),
        migrations.RemoveField(
            model_name='category',
            name='classname_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='classname_hy',
        ),
    ]
