# Generated by Django 4.1.7 on 2023-04-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_category_classname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='SubCategory price'),
        ),
    ]
