# Generated by Django 4.1.7 on 2023-04-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_subcategory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Item name')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Item price')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='Item image')),
                ('img_logo', models.ImageField(blank=True, upload_to='images', verbose_name='Item sale image')),
            ],
            options={
                'verbose_name': 'Items',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
