# Generated by Django 4.1.7 on 2023-04-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.EmailField(max_length=254, verbose_name='User email')),
                ('subject', models.CharField(max_length=50, verbose_name='User name')),
                ('message', models.TextField(verbose_name='User message')),
            ],
            options={
                'verbose_name': 'ContactUs',
                'verbose_name_plural': 'ContactUs',
            },
        ),
    ]
