# Generated by Django 4.1.7 on 2023-05-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_curency'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerinfo',
            name='country3_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country 3'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='country3_hy',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country 3'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='account',
            field=models.CharField(max_length=50, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='account_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='account_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Curency 1'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Curency 2'),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='curency3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Curency 3'),
        ),
    ]
