# Generated by Django 4.1.7 on 2023-05-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_headerinfo_country3_en_headerinfo_country3_hy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslider',
            name='img',
            field=models.ImageField(upload_to='images', verbose_name='Slider image1'),
        ),
        migrations.AlterField(
            model_name='homeslider',
            name='img_logo',
            field=models.ImageField(upload_to='images', verbose_name='Slider image2'),
        ),
    ]
